name: CI/CD - Node.js Project with Heroku Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Lint the code (optional - include only if you have a lint script)
      - name: Run linter
        run: npm run lint
        continue-on-error: true  # Optional: don’t fail build if lint has issues

  
